apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-api-virtual-service-main
spec:
  gateways:
  - acctrainings-gateway-main
  hosts:
  - '*.apps.azureneocp.neinnovation-ocp.com'
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percentage:
          value: 100
    route:
    - destination:
        host: customer-api-main