apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-api-virtual-service-pod05
spec:
  gateways:
  - acctrainings-gateway-pod05
  hosts:
  - '*.apps.awsopenshift.ne-innovation.com'
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percentage:
          value: 100
    route:
    - destination:
        host: customer-api-pod05
