apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: policy-api-virtual-service-pod01
spec:
  hosts:
  - "*"
  gateways:
  - acctrainings-gateway-pod01
  http:
  - match:
    - uri:
        prefix: /api/pod01/policy
    route:
    - destination:
        host: policy-api-pod01
        port:
          number: 8080
    timeout: 5s
    retries:
      attempts: 3
      perTryTimeout: 2s
     
