apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: policy-api-virtual-service-pod05
spec:
  gateways:
      - acctrainings-gateway-pod05
  hosts:
      - '*.apps.azureneocp.neinnovation-ocp.com'
  http:
      - match:
          - uri:
              prefix: /api/pod05/policy
        route:
          - destination:
              host: policy-api-pod05
              port:
               number: 8080
              subset: v1
            weight: 80
          - destination:
              host: policy-api-pod05
              port:
               number: 8080
              subset: v2
            weight: 20