# Service and Deployment configuration for Policy service deployment.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-api-pod03
---
##################################################################################################
# Policy service V2
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-api-release-2.0.0
  labels:
    app: policy-api-pod03
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-api-pod03
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: policy-api-pod03
        version: v2
    spec:
      serviceAccountName: policy-api-pod03
      containers:
      - name: policy-api-pod03
        image: quay.io/acctrainings/policy-api-gold:release-2.0.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: policy-api-pod03
        ports:
        - containerPort: 8080