apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: policy-api
spec:
  host: policy-api
  trafficPolicy:
    loadBalancer:
      simple: RANDOM #ROUND_ROBIN #Load Balancing
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2