apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: policy-api-virtual-service-pod02
spec:
  gateways:
      - acctrainings-gateway-pod02
  hosts:
      - '*.apps.awsopenshift.ne-innovation.com'
  http:
      - match:
          - uri:
              prefix: /api/pod02/policy
        route:
          - destination:
              host: policy-api-pod02
              port:
               number: 8080
              subset: v1
            weight: 80
          - destination:
              host: policy-api-pod02
              port:
               number: 8080
              subset: v2
            weight: 20
