apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-api-virtual-service-main
spec:
  hosts:
  - '*.apps.azureneocp.neinnovation-ocp.com'
  gateways:
  - acctrainings-gateway-main
  http:
  - match:
    - uri:
        prefix: /api/main/customer
    route:
    - destination:
        host: customer-api-main
        port:
          number: 8080
