apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-api-virtual-service
spec:
  hosts:
  - '*.apps.awsopenshift.ne-innovation.com'
  gateways:
  - acctrainings-gateway
  http:
  - match:
    - uri:
        prefix: /customer
    route:
    - destination:
        host: customer-api
        port:
          number: 8080