apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: policy-api-virtual-service-pod05
spec:
  gateways:
    - acctrainings-gateway-pod05
  hosts:
    - '*.apps.awsopenshift.ne-innovation.com'
  http:
    - match:
        - uri:
            prefix: /api/pod05/policy
      route:
        - destination:
            host: policy-api-pod05
            port:
              number: 8080
