apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: policy-api-virtual-service-main
spec:
  gateways:
    - acctrainings-gateway-main
  hosts:
    - '*.apps.awsopenshift.ne-innovation.com'
  http:
    - match:
        - uri:
            prefix: /api/main/policy
      route:
        - destination:
            host: policy-api-main
            port:
              number: 8080
